### DISCUSSION TITLE
Unable to install meeds-gamification

### DISCUSSION THREAD

**Discussion by aimanskie** [exoplatform/exo-community#65] [Q&A]
Hello, eXo Community!

I'm encountering an issue with configuring the gamification add-on in my `docker-compose` setup. Despite following the documentation, I'm running into an error that I can't seem to resolve on my own.

### Error Details
The system is not recognizing the gamification add-on identifier as valid. Here's the error message I'm getting (see screenshot for reference):

![Error Screenshot](https://github.com/exoplatform/exo-community/assets/86446622/65e34f33-842b-48ec-8851-f906cf31de7f)

### Documentation Reference
I used the identifier specified in the [eXo Platform upgrade documentation](https://github.com/exoplatform/exo-documentation/blob/c44ad9a0b1154e2b99def449eb8f91bb775e2d0b/docs/Upgrade.rst#id33), which suggests using `meeds-gamification`.

### Docker-Compose Configuration
Here's the relevant part of my `docker-compose.yml`:

```yaml
environment:
  EXO_ADDONS_LIST: "meeds-gamification,meeds-kudos,meeds-perk-store,meeds-app-center,meeds-es-embedded,meeds-push-notification,meeds-wallet"
  EXO_ADDONS_REMOVE_LIST: "exo-onlyoffice"
  ```

Any insights or suggestions would be greatly appreciated!

Thank you in advance for your help.
