### DISCUSSION TITLE
Existing built Portlets NOT showing and layout back to default after stop-start or fresh exo docker container

### DISCUSSION THREAD

**Discussion by aimanskie** [exoplatform/exo-community#75] [Q&A]
Hi Exo Community!, 

As mentioned in the title, we're using and building new portlets and need to insert the porlets in the exo-1>files>opt>exo>webapps (attached for preview) to test. So i will restart container to make sure the installed portlets are in the registry. However, after restart the previous portlets would not be shown based on the edit layouts that the previous portlets has been assigned to. So basically it will be such a headache to maintain and develop as whatever changes in layouts should persist.  The image shows that user management is showing instead of new user management when container restarted.

<img width="710" alt="image" src="https://github.com/exoplatform/exo-community/assets/86446622/013636e7-2c25-44b4-9fed-e1dcd7197816">

<img width="1698" alt="image" src="https://github.com/exoplatform/exo-community/assets/86446622/296bc761-f385-4054-849e-f3d3edffeb55">

This is the docker compose, assuming it has to do with this.
```
version: '2.3'
services:
  web:
    image: exoplatform/nginx:1.24.0
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - exo
  exo:
    image: exoplatform/exo-community:6.4
    environment:
      EXO_PROXY_VHOST: localhost
      EXO_PROXY_PORT: 80
      EXO_DB_HOST: mysql
      EXO_PROXY_SSL: "false"
      EXO_DB_TYPE: mysql
      EXO_DB_NAME: exo
      EXO_DB_USER: exo
      EXO_DB_PASSWORD: my-secret-pw
      EXO_ADDONS_LIST: ""
      EXO_ADDONS_NOCOMPAT_MODE: "true"
      EXO_JVM_LOG_GC_ENABLED: "true"
      EXO_ES_HOST: es
      EXO_MONGO_HOST: mongo
      EXO_MONGO_PORT: 27017
      EXO_MONGO_DB_NAME: chat
    ports:
      - "8080:8080"
    volumes:
      - exo_data:/srv/exo
      - exo_logs:/var/log/exo
    depends_on:
      - mysql
      - mongo
      - es
  mysql:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: my-super-secret-pw
      MYSQL_DATABASE: exo
      MYSQL_USER: exo
      MYSQL_PASSWORD: my-secret-pw
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  es:
    image: exoplatform/elasticsearch:2.1.0
    volumes:
      - search_data:/usr/share/elasticsearch/data:rw
    environment:
      - ES_JAVA_OPTS=-Xms2048m -Xmx2048m
      - node.name=exo
      - cluster.name=exo
      - cluster.initial_master_nodes=exo
      - network.host=_site_
      - xpack.security.enabled=false
  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo_data:/data/db:rw
volumes:
  exo_data:
  exo_logs:
  mysql_data:
  search_data:
  mongo_data:
  ```
